# if your site is in 'https', then make sure your base url isn't written using 'http' otherwise your sitemap would contain http (as opposeed to https) URLs. This would affect Google indexing of your URLs.
baseURL: https://zaheenadeep.github.io/
title: Zaheen Ahmed Deep
# paginate: 5
theme: charlolamode

menu:
  main:
    - name: Contact
      url: /contact/
      weight: 30

params:
  defaultTheme: auto
  profileMode:
    # Disable to populate home page with 'mainSections' content
    enabled: true
    title: Zaheen Ahmed Deep
    description:    
      Hi, I'm Zaheen, an Associate Systems Engineer in the Infrastructure Team of [CoStar Group](https://www.costargroup.com/).
    imageUrl: "/images/cropdeep.jpg"
    imageTitle: Zaheen Ahmed Deep
    buttons:
  socialIcons:
    - name: github
      url: "https://github.com/zaheenadeep"
    - name: linkedin
      url: "https://www.linkedin.com/in/zaheenadeep/"
    - name: youtube
      url: "https://www.youtube.com/@zadspecial"

enableInlineShortcodes: true
enableRobotsTXT: true
enableEmoji: true
pygmentsUseClasses: true

minify:
    disableXML: true
